### ISSUE TITLE
Non-Boolean Reply 

### ISSUE THREAD

**Issue by Mixddux** [chrismuiruriz/ConvoJs#2]
Hi, and thanks for this; it's awesome!

Not that this is an 'issue' per say, but what if I wanted a response that isn't correct / wrong? Like if I wanted to access any input and store it as a variable - how would I code that?

Example:
"Hi, what's your name?"

                        "Michael"

"Hi **Michael**, nice to meet you."

Thank you for your help!

**Comment by chrismuiruriz** [comment]
Hi @Mixddux for such a dynamic feature I would advise you to have a look at https://github.com/space10-community/conversational-form.
